-- APT Defender Supabase Schema (PostgreSQL)
-- Run this in your Supabase SQL Editor

-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- DEVICES
create table public.devices (
    id bigint generated by default as identity primary key,
    hostname text not null,
    os text not null,
    os_version text,
    ip_address text,
    status text default 'offline',
    last_seen timestamptz default now(),
    paired_at timestamptz default now(),
    active_threats int default 0,
    tags text[],
    user_id uuid references auth.users(id)
);
alter table public.devices enable row level security;
create policy "Users can view own devices" on public.devices for select using (auth.uid() = user_id);
create policy "Users can insert own devices" on public.devices for insert with check (auth.uid() = user_id);
create policy "Users can update own devices" on public.devices for update using (auth.uid() = user_id);

-- THREATS
create table public.threats (
    id bigint generated by default as identity primary key,
    device_id bigint references public.devices(id) on delete cascade not null,
    severity int not null,
    type text not null,
    explanation text not null,
    file_path text,
    detected_at timestamptz default now(),
    dismissed boolean default false,
    dismissed_at timestamptz
);
alter table public.threats enable row level security;
create policy "Users can view threats for own devices" on public.threats for select using (
    exists (select 1 from public.devices where id = threats.device_id and user_id = auth.uid())
);

-- ALERTS (Real-time notifications)
create table public.alerts (
    id bigint generated by default as identity primary key,
    device_id bigint references public.devices(id) on delete cascade,
    title text not null,
    message text not null,
    created_at timestamptz default now(),
    read boolean default false
);
alter table public.alerts enable row level security;
create policy "Users can view alerts for own devices" on public.alerts for select using (
    exists (select 1 from public.devices where id = alerts.device_id and user_id = auth.uid())
);

-- ACTIONS LOG
create table public.action_logs (
    id bigint generated by default as identity primary key,
    device_id bigint references public.devices(id) on delete cascade,
    action_type text not null,
    target text not null,
    status text not null,
    timestamp timestamptz default now()
);
alter table public.action_logs enable row level security;
create policy "Users can view logs for own devices" on public.action_logs for select using (
    exists (select 1 from public.devices where id = action_logs.device_id and user_id = auth.uid())
);
